services:
  app:
    image: belajar-app:${TAG:?TAG belum diisi}
    build: .
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env
      - storage:/var/www/storage
      - data:/var/www/data

  nginx:
    image: belajar-nginx:${TAG:?TAG belum diisi}
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - storage:/var/www/storage:ro
    depends_on:
      - app

volumes:
  storage:
  data: